create table if not exists public.eligibility_checks (
  id bigint generated by default as identity primary key,
  address text not null unique,
  eligible boolean not null default true,
  successful_transactions integer not null default 10,
  submitted_at timestamptz not null default now()
);

create index if not exists eligibility_checks_address_idx
on public.eligibility_checks(address);

alter table public.eligibility_checks enable row level security;

-- No public policies are created.
-- The Edge Function writes with SUPABASE_SERVICE_ROLE_KEY.
