const Rhood=(()=>{const CHAIN_ID='0x1237';const CHAIN={chainId:CHAIN_ID,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:['https://robinhoodchain.blockscout.com']};const CONTRACT='0x6be906e10351B4a970521c386E89D9e4e34c47C9';const ABI=['function balanceOf(address owner) view returns (uint256)'];let provider=null;let signer=null;let address=null;let balance=0;
function short(a){return a?a.slice(0,6)+'…'+a.slice(-4):'—'}
function path(){return location.pathname}
function gateSession(){return localStorage.getItem('rhood_verified')==='1'}
async function ensureChain(){if(!window.ethereum)throw new Error('No browser wallet detected.');try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN_ID}]})}catch(e){if(e.code===4902||e.message?.includes('Unrecognized chain'))await window.ethereum.request({method:'wallet_addEthereumChain',params:[CHAIN]});else throw e}}
async function connect(){if(!window.ethereum){throw new Error('No injected wallet found in this browser. Open this site inside MetaMask/Rabby/OKX wallet browser, or use the MetaMask button below.')}await window.ethereum.request({method:'eth_requestAccounts'});await ensureChain();provider=new ethers.BrowserProvider(window.ethereum);signer=await provider.getSigner();address=await signer.getAddress();const c=new ethers.Contract(CONTRACT,ABI,provider);const b=await c.balanceOf(address);balance=Number(b);if(balance<=0){localStorage.removeItem('rhood_verified');throw new Error('This wallet does not hold a RhoodStone NFT.');}localStorage.setItem('rhood_verified','1');localStorage.setItem('rhood_address',address);localStorage.setItem('rhood_balance',String(balance));return {address,balance}}
function openWallet(){const d=location.host+location.pathname+location.search;location.href='https://metamask.app.link/dapp/'+d}
function bindEvents(){if(window.ethereum){window.ethereum.on?.('accountsChanged',()=>{localStorage.removeItem('rhood_verified');location.href='/'});window.ethereum.on?.('chainChanged',()=>location.reload())}}
async function initGate(){const btn=document.getElementById('connectBtn'),st=document.getElementById('walletStatus'),help=document.getElementById('walletHelp');if(gateSession()){}btn?.addEventListener('click',async()=>{btn.disabled=true;st.textContent='Connecting wallet…';help.textContent='';try{const r=await connect();st.textContent=`Verified • ${short(r.address)} • ${r.balance} Stone`;location.href='/portal/'}catch(e){st.textContent='Verification failed';help.textContent=e.message||String(e)}finally{btn.disabled=false}});if(!window.ethereum)help.innerHTML='No injected wallet was detected. If you are on Chrome mobile, open this page from the MetaMask wallet browser.';bindEvents()}
function requireHolder(){if(!gateSession()){location.replace('/');return false}return true}
function nav(){const p=path();return `<aside class="sidebar" id="sidebar"><div class="brand"><div class="mini">RS</div><div><strong>RHOODSTONE</strong><small>HOLDER SPACE</small></div></div><nav class="nav"><div class="nav-label">STONE</div><a href="/portal/" data-path="/portal/">Dashboard</a><a href="/benefits/" data-path="/benefits/">Benefits</a><a href="/opportunities/" data-path="/opportunities/">WL & GTD</a><a href="/partners/" data-path="/partners/">Partners</a><div class="nav-label">HOLDER</div><a href="/points/" data-path="/points/">Points</a><a href="/rewards/" data-path="/rewards/">Rewards</a><a href="/passport/" data-path="/passport/">Passport</a><a href="/tiers/" data-path="/tiers/">Tiers</a><a href="/activity/" data-path="/activity/">Activity</a></nav><div class="wallet-card"><div class="label">VERIFIED WALLET</div><div class="addr" id="sideAddr">—</div><div class="balance" id="sideBalance">— Stone</div></div></aside>`}
function layout(title,desc,body){if(!requireHolder())return '';const addr=localStorage.getItem('rhood_address');const bal=localStorage.getItem('rhood_balance')||'0';return `<div class="app">${nav()}<main class="main"><div class="top"><div><div class="crumb">RHOODSTONE / HOLDER</div><h1 class="page-title">${title}</h1><div class="page-desc">${desc}</div></div><button class="btn mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('open')">MENU</button></div>${body}</main></div><script>document.getElementById('sideAddr').textContent='${short(addr)}';document.getElementById('sideBalance').textContent='${bal} Stone';document.querySelectorAll('.nav a').forEach(a=>{if(a.dataset.path==='${path()}')a.classList.add('active')});</script>`}
function renderPage(title,desc,body){document.body.innerHTML=layout(title,desc,body);bindEvents()}
return {initGate,connect,openWallet,renderPage,requireHolder,short,CONTRACT}})();
